import json
import os
import sqlite3
from contextlib import contextmanager
from datetime import datetime, timezone


SQLITE_SCHEMA = """
CREATE TABLE IF NOT EXISTS collection_runs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  started_at TEXT NOT NULL,
  finished_at TEXT,
  status TEXT NOT NULL,
  source_errors TEXT NOT NULL DEFAULT '[]'
);

CREATE TABLE IF NOT EXISTS neon_egress_hourly (
  hour TEXT NOT NULL,
  project_id TEXT NOT NULL,
  branch_id TEXT,
  public_bytes INTEGER NOT NULL DEFAULT 0,
  private_bytes INTEGER NOT NULL DEFAULT 0,
  total_bytes INTEGER NOT NULL DEFAULT 0,
  source_granularity TEXT NOT NULL,
  collected_at TEXT NOT NULL,
  PRIMARY KEY (hour, project_id, branch_id, source_granularity)
);

CREATE TABLE IF NOT EXISTS neon_transfer_counters (
  collected_at TEXT NOT NULL,
  project_id TEXT NOT NULL,
  branch_id TEXT,
  data_transfer_bytes INTEGER NOT NULL,
  source TEXT NOT NULL,
  counter_reset INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (collected_at, project_id, branch_id, source)
);

CREATE TABLE IF NOT EXISTS cloud_run_hourly (
  hour TEXT NOT NULL,
  resource_type TEXT NOT NULL,
  resource_name TEXT NOT NULL,
  requests INTEGER NOT NULL DEFAULT 0,
  runtime_seconds REAL NOT NULL DEFAULT 0,
  cpu REAL NOT NULL DEFAULT 0,
  memory_gib REAL NOT NULL DEFAULT 0,
  vcpu_seconds REAL NOT NULL DEFAULT 0,
  gib_seconds REAL NOT NULL DEFAULT 0,
  executions INTEGER NOT NULL DEFAULT 0,
  near_timeout_count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (hour, resource_type, resource_name)
);

CREATE TABLE IF NOT EXISTS cloud_run_job_executions (
  execution_name TEXT PRIMARY KEY,
  job_name TEXT NOT NULL,
  region TEXT NOT NULL,
  started_at TEXT NOT NULL,
  completed_at TEXT NOT NULL,
  status TEXT NOT NULL,
  cpu REAL NOT NULL DEFAULT 0,
  memory_gib REAL NOT NULL DEFAULT 0,
  billed_seconds REAL NOT NULL DEFAULT 0,
  app_runtime_seconds REAL,
  overhead_seconds REAL,
  billed_vcpu_seconds REAL NOT NULL DEFAULT 0,
  billed_gib_seconds REAL NOT NULL DEFAULT 0,
  app_vcpu_seconds REAL,
  app_gib_seconds REAL,
  overhead_vcpu_seconds REAL,
  overhead_gib_seconds REAL,
  collected_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS llm_usage_hourly (
  hour TEXT NOT NULL,
  activity TEXT NOT NULL,
  mode TEXT NOT NULL,
  provider TEXT NOT NULL,
  model TEXT NOT NULL,
  operation TEXT NOT NULL,
  requests INTEGER NOT NULL,
  prompt_tokens INTEGER NOT NULL,
  completion_tokens INTEGER NOT NULL,
  total_tokens INTEGER NOT NULL,
  PRIMARY KEY (hour, activity, mode, provider, model, operation)
);

CREATE TABLE IF NOT EXISTS postgres_metrics (
  collected_at TEXT NOT NULL,
  metric_name TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_name TEXT NOT NULL,
  numeric_value REAL NOT NULL,
  unit TEXT NOT NULL,
  PRIMARY KEY (collected_at, metric_name, entity_type, entity_name)
);

CREATE TABLE IF NOT EXISTS source_errors (
  collected_at TEXT NOT NULL,
  source TEXT NOT NULL,
  redacted_error_message TEXT NOT NULL
);
"""


POSTGRES_SCHEMA = """
CREATE SCHEMA IF NOT EXISTS diagnostics;
SET search_path TO diagnostics;

CREATE TABLE IF NOT EXISTS collection_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at TEXT NOT NULL,
  finished_at TEXT,
  status TEXT NOT NULL,
  source_errors TEXT NOT NULL DEFAULT '[]'
);

CREATE TABLE IF NOT EXISTS neon_egress_hourly (
  hour TEXT NOT NULL,
  project_id TEXT NOT NULL,
  branch_id TEXT,
  public_bytes BIGINT NOT NULL DEFAULT 0,
  private_bytes BIGINT NOT NULL DEFAULT 0,
  total_bytes BIGINT NOT NULL DEFAULT 0,
  source_granularity TEXT NOT NULL,
  collected_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS neon_egress_hourly_key
  ON neon_egress_hourly (hour, project_id, branch_id, source_granularity) NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS neon_transfer_counters (
  collected_at TEXT NOT NULL,
  project_id TEXT NOT NULL,
  branch_id TEXT,
  data_transfer_bytes BIGINT NOT NULL,
  source TEXT NOT NULL,
  counter_reset INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS neon_transfer_counters_key
  ON neon_transfer_counters (collected_at, project_id, branch_id, source) NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS cloud_run_hourly (
  hour TEXT NOT NULL,
  resource_type TEXT NOT NULL,
  resource_name TEXT NOT NULL,
  requests BIGINT NOT NULL DEFAULT 0,
  runtime_seconds DOUBLE PRECISION NOT NULL DEFAULT 0,
  cpu DOUBLE PRECISION NOT NULL DEFAULT 0,
  memory_gib DOUBLE PRECISION NOT NULL DEFAULT 0,
  vcpu_seconds DOUBLE PRECISION NOT NULL DEFAULT 0,
  gib_seconds DOUBLE PRECISION NOT NULL DEFAULT 0,
  executions BIGINT NOT NULL DEFAULT 0,
  near_timeout_count BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (hour, resource_type, resource_name)
);

CREATE TABLE IF NOT EXISTS cloud_run_job_executions (
  execution_name TEXT PRIMARY KEY,
  job_name TEXT NOT NULL,
  region TEXT NOT NULL,
  started_at TEXT NOT NULL,
  completed_at TEXT NOT NULL,
  status TEXT NOT NULL,
  cpu DOUBLE PRECISION NOT NULL DEFAULT 0,
  memory_gib DOUBLE PRECISION NOT NULL DEFAULT 0,
  billed_seconds DOUBLE PRECISION NOT NULL DEFAULT 0,
  app_runtime_seconds DOUBLE PRECISION,
  overhead_seconds DOUBLE PRECISION,
  billed_vcpu_seconds DOUBLE PRECISION NOT NULL DEFAULT 0,
  billed_gib_seconds DOUBLE PRECISION NOT NULL DEFAULT 0,
  app_vcpu_seconds DOUBLE PRECISION,
  app_gib_seconds DOUBLE PRECISION,
  overhead_vcpu_seconds DOUBLE PRECISION,
  overhead_gib_seconds DOUBLE PRECISION,
  collected_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS postgres_metrics (
  collected_at TEXT NOT NULL,
  metric_name TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_name TEXT NOT NULL,
  numeric_value DOUBLE PRECISION NOT NULL,
  unit TEXT NOT NULL,
  PRIMARY KEY (collected_at, metric_name, entity_type, entity_name)
);

CREATE TABLE IF NOT EXISTS source_errors (
  collected_at TEXT NOT NULL,
  source TEXT NOT NULL,
  redacted_error_message TEXT NOT NULL
);
"""


class PostgresConnection:
    def __init__(self, conn):
        self.conn = conn

    def execute(self, sql, params=None):
        return self.conn.execute(sql.replace("?", "%s"), params)

    def executemany(self, sql, rows):
        return self.conn.executemany(sql.replace("?", "%s"), rows)

    def executescript(self, sql):
        with self.conn.cursor() as cur:
            for statement in sql.split(";"):
                statement = statement.strip()
                if statement:
                    cur.execute(statement)


def utc_now():
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


@contextmanager
def connect(path):
    storage = os.environ.get("DIAGNOSTICS_STORAGE", "sqlite").strip().lower()
    if storage == "postgres":
        import psycopg

        url = os.environ.get("DIAGNOSTICS_DATABASE_URL") or os.environ["DATABASE_URL"]
        conn = psycopg.connect(url)
        try:
            yield PostgresConnection(conn)
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        finally:
            conn.close()
        return

    if storage != "sqlite":
        raise ValueError(f"Unsupported DIAGNOSTICS_STORAGE: {storage}")

    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    try:
        conn.execute("PRAGMA journal_mode=WAL")
        conn.execute("PRAGMA foreign_keys=ON")
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def migrate(conn):
    if isinstance(conn, PostgresConnection):
        conn.executescript(POSTGRES_SCHEMA)
    else:
        conn.executescript(SQLITE_SCHEMA)


def start_run(conn):
    started_at = utc_now()
    if isinstance(conn, PostgresConnection):
        cur = conn.execute(
            "INSERT INTO collection_runs (started_at, status) VALUES (?, ?) RETURNING id",
            (started_at, "running"),
        )
        return cur.fetchone()[0]

    cur = conn.execute(
        "INSERT INTO collection_runs (started_at, status) VALUES (?, ?)",
        (started_at, "running"),
    )
    return cur.lastrowid


def finish_run(conn, run_id, status, source_errors):
    conn.execute(
        "UPDATE collection_runs SET finished_at = ?, status = ?, source_errors = ? WHERE id = ?",
        (utc_now(), status, json.dumps(source_errors, sort_keys=True), run_id),
    )


def record_source_error(conn, source, message):
    conn.execute(
        "INSERT INTO source_errors (collected_at, source, redacted_error_message) VALUES (?, ?, ?)",
        (utc_now(), source, message),
    )


def upsert_many(conn, sql, rows):
    if rows:
        conn.executemany(sql, rows)
